export interface Career {
  id: string
  title: string
  category: string
  description: string
  skills: string[]
  salaryRange: string
  demand: "high" | "medium" | "growing"
  experience: "entry" | "mid" | "senior" | "lead"
}

export const careers: Career[] = [
  // Data Science & Analytics
  {
    id: "data-scientist",
    title: "Data Scientist",
    category: "Data Science & Analytics",
    description: "Analyze complex data to help organizations make better decisions using statistical methods and ML.",
    skills: ["Python", "Statistics", "Machine Learning", "SQL", "Data Visualization"],
    salaryRange: "$95K - $165K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "ml-engineer",
    title: "Machine Learning Engineer",
    category: "Data Science & Analytics",
    description: "Design, build, and deploy machine learning models and systems at scale.",
    skills: ["Python", "TensorFlow/PyTorch", "MLOps", "Cloud Platforms", "Data Engineering"],
    salaryRange: "$120K - $200K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "data-analyst",
    title: "Data Analyst",
    category: "Data Science & Analytics",
    description: "Interpret data and turn it into actionable insights for business decisions.",
    skills: ["SQL", "Excel", "Tableau/Power BI", "Statistics", "Python"],
    salaryRange: "$60K - $100K",
    demand: "high",
    experience: "entry",
  },
  {
    id: "business-intelligence",
    title: "Business Intelligence Analyst",
    category: "Data Science & Analytics",
    description: "Create dashboards and reports to help organizations understand their data.",
    skills: ["SQL", "BI Tools", "Data Modeling", "ETL", "Business Acumen"],
    salaryRange: "$70K - $120K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "quantitative-analyst",
    title: "Quantitative Analyst",
    category: "Data Science & Analytics",
    description: "Apply mathematical and statistical models to financial and risk management problems.",
    skills: ["Mathematics", "Statistics", "Python/R", "Finance", "ML"],
    salaryRange: "$100K - $200K",
    demand: "medium",
    experience: "mid",
  },

  // AI/ML Research
  {
    id: "ai-researcher",
    title: "AI Research Scientist",
    category: "AI/ML Research",
    description: "Conduct cutting-edge research to advance the field of artificial intelligence.",
    skills: ["Deep Learning", "Mathematics", "Research Methods", "PyTorch", "Publications"],
    salaryRange: "$150K - $300K",
    demand: "high",
    experience: "senior",
  },
  {
    id: "research-engineer",
    title: "Research Engineer",
    category: "AI/ML Research",
    description: "Bridge the gap between research and production by implementing novel algorithms.",
    skills: ["Python", "C++", "Deep Learning", "Distributed Systems", "Research"],
    salaryRange: "$130K - $220K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "nlp-researcher",
    title: "NLP Research Scientist",
    category: "AI/ML Research",
    description: "Advance the field of natural language processing through research.",
    skills: ["NLP", "Transformers", "Linguistics", "Python", "Research"],
    salaryRange: "$140K - $250K",
    demand: "high",
    experience: "senior",
  },
  {
    id: "cv-researcher",
    title: "Computer Vision Researcher",
    category: "AI/ML Research",
    description: "Research and develop new computer vision algorithms and architectures.",
    skills: ["Computer Vision", "Deep Learning", "PyTorch", "Mathematics", "Research"],
    salaryRange: "$140K - $250K",
    demand: "high",
    experience: "senior",
  },

  // Engineering Roles
  {
    id: "ai-engineer",
    title: "AI Engineer",
    category: "Engineering",
    description: "Build and integrate AI capabilities into products and services.",
    skills: ["Python", "ML Frameworks", "APIs", "Cloud", "Software Engineering"],
    salaryRange: "$110K - $180K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "deep-learning-engineer",
    title: "Deep Learning Engineer",
    category: "Engineering",
    description: "Specialize in designing and implementing deep neural network architectures.",
    skills: ["PyTorch/TensorFlow", "Neural Networks", "GPU Computing", "Python", "Math"],
    salaryRange: "$130K - $210K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "nlp-engineer",
    title: "NLP Engineer",
    category: "Engineering",
    description: "Build systems that understand and generate human language.",
    skills: ["NLP", "Transformers", "Python", "Hugging Face", "LLMs"],
    salaryRange: "$120K - $190K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "cv-engineer",
    title: "Computer Vision Engineer",
    category: "Engineering",
    description: "Develop systems that can interpret and analyze visual information.",
    skills: ["Computer Vision", "OpenCV", "Deep Learning", "Python", "C++"],
    salaryRange: "$115K - $185K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "robotics-engineer",
    title: "Robotics Engineer",
    category: "Engineering",
    description: "Design and build intelligent robotic systems with AI capabilities.",
    skills: ["ROS", "Control Systems", "Python/C++", "Computer Vision", "Sensors"],
    salaryRange: "$100K - $170K",
    demand: "growing",
    experience: "mid",
  },
  {
    id: "mlops-engineer",
    title: "MLOps Engineer",
    category: "Engineering",
    description: "Build and maintain infrastructure for ML model training and deployment.",
    skills: ["Kubernetes", "Docker", "CI/CD", "Cloud", "Python"],
    salaryRange: "$120K - $190K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "data-engineer",
    title: "Data Engineer",
    category: "Engineering",
    description: "Build and maintain data pipelines and infrastructure for AI systems.",
    skills: ["SQL", "Spark", "Airflow", "Cloud", "Python"],
    salaryRange: "$100K - $170K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "platform-engineer",
    title: "AI Platform Engineer",
    category: "Engineering",
    description: "Build platforms and tools that enable AI/ML development at scale.",
    skills: ["Kubernetes", "Cloud", "Distributed Systems", "Python", "Infrastructure"],
    salaryRange: "$130K - $200K",
    demand: "growing",
    experience: "senior",
  },

  // Product & Strategy
  {
    id: "ai-product-manager",
    title: "AI Product Manager",
    category: "Product & Strategy",
    description: "Define and drive the strategy for AI-powered products.",
    skills: ["Product Strategy", "AI/ML Knowledge", "Communication", "Data Analysis", "UX"],
    salaryRange: "$130K - $200K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "ai-strategy-lead",
    title: "AI Strategy Lead",
    category: "Product & Strategy",
    description: "Develop and execute AI strategy at the organizational level.",
    skills: ["Strategy", "AI/ML Knowledge", "Leadership", "Business Acumen", "Communication"],
    salaryRange: "$150K - $250K",
    demand: "growing",
    experience: "lead",
  },
  {
    id: "technical-pm",
    title: "Technical Program Manager (AI)",
    category: "Product & Strategy",
    description: "Coordinate complex AI/ML projects across multiple teams.",
    skills: ["Program Management", "Technical Knowledge", "Communication", "Agile", "Leadership"],
    salaryRange: "$120K - $180K",
    demand: "medium",
    experience: "senior",
  },

  // Specialized Roles
  {
    id: "prompt-engineer",
    title: "Prompt Engineer",
    category: "Specialized",
    description: "Design and optimize prompts for large language models.",
    skills: ["LLMs", "Prompt Design", "NLP", "Python", "Evaluation"],
    salaryRange: "$90K - $180K",
    demand: "growing",
    experience: "mid",
  },
  {
    id: "ai-ethicist",
    title: "AI Ethics Researcher",
    category: "Specialized",
    description: "Ensure AI systems are developed and deployed responsibly and ethically.",
    skills: ["Ethics", "AI/ML Knowledge", "Policy", "Research", "Communication"],
    salaryRange: "$100K - $180K",
    demand: "growing",
    experience: "mid",
  },
  {
    id: "ai-safety-researcher",
    title: "AI Safety Researcher",
    category: "Specialized",
    description: "Research ways to make AI systems safer and more aligned with human values.",
    skills: ["AI Safety", "Research", "Mathematics", "ML", "Philosophy"],
    salaryRange: "$120K - $250K",
    demand: "growing",
    experience: "senior",
  },
  {
    id: "conversational-ai",
    title: "Conversational AI Developer",
    category: "Specialized",
    description: "Build chatbots, voice assistants, and conversational interfaces.",
    skills: ["NLP", "Dialog Systems", "Python", "APIs", "UX Design"],
    salaryRange: "$90K - $160K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "speech-engineer",
    title: "Speech/Audio ML Engineer",
    category: "Specialized",
    description: "Develop speech recognition, synthesis, and audio processing systems.",
    skills: ["Speech Recognition", "Audio Processing", "Deep Learning", "Python", "DSP"],
    salaryRange: "$110K - $180K",
    demand: "medium",
    experience: "mid",
  },

  // Industry-Specific
  {
    id: "healthcare-ai",
    title: "Healthcare AI Specialist",
    category: "Industry-Specific",
    description: "Apply AI to healthcare problems like diagnosis and drug discovery.",
    skills: ["ML", "Healthcare Domain", "Medical Imaging", "Python", "Regulations"],
    salaryRange: "$120K - $200K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "fintech-ai",
    title: "FinTech AI Engineer",
    category: "Industry-Specific",
    description: "Build AI systems for financial services like fraud detection and trading.",
    skills: ["ML", "Finance Domain", "Python", "Risk Modeling", "Regulations"],
    salaryRange: "$130K - $220K",
    demand: "high",
    experience: "mid",
  },
  {
    id: "autonomous-vehicle",
    title: "Autonomous Vehicle Engineer",
    category: "Industry-Specific",
    description: "Develop perception and planning systems for self-driving vehicles.",
    skills: ["Computer Vision", "Sensor Fusion", "C++", "ROS", "Deep Learning"],
    salaryRange: "$140K - $230K",
    demand: "high",
    experience: "senior",
  },
  {
    id: "gaming-ai",
    title: "Game AI Developer",
    category: "Industry-Specific",
    description: "Create intelligent behaviors and systems for video games.",
    skills: ["Game Development", "RL", "C++/C#", "Behavior Trees", "Pathfinding"],
    salaryRange: "$80K - $150K",
    demand: "medium",
    experience: "mid",
  },

  // Leadership
  {
    id: "head-of-ai",
    title: "Head of AI",
    category: "Leadership",
    description: "Lead the AI function and strategy for an organization.",
    skills: ["Leadership", "AI Strategy", "Team Building", "Technical Vision", "Business Acumen"],
    salaryRange: "$200K - $400K",
    demand: "medium",
    experience: "lead",
  },
  {
    id: "chief-data-officer",
    title: "Chief Data Officer",
    category: "Leadership",
    description: "Oversee data strategy, governance, and analytics for an organization.",
    skills: ["Data Strategy", "Leadership", "Governance", "Analytics", "Business"],
    salaryRange: "$250K - $500K",
    demand: "medium",
    experience: "lead",
  },
  {
    id: "ml-manager",
    title: "ML Engineering Manager",
    category: "Leadership",
    description: "Lead and grow a team of ML engineers building AI products.",
    skills: ["Leadership", "ML Systems", "People Management", "Technical Vision", "Delivery"],
    salaryRange: "$180K - $280K",
    demand: "high",
    experience: "lead",
  },
  {
    id: "research-lead",
    title: "AI Research Lead",
    category: "Leadership",
    description: "Lead a team of AI researchers on cutting-edge projects.",
    skills: ["Research Leadership", "Deep Learning", "Publications", "Team Building", "Vision"],
    salaryRange: "$200K - $350K",
    demand: "medium",
    experience: "lead",
  },
]

export const demandColors = {
  high: "bg-accent/20 text-accent",
  medium: "bg-secondary/20 text-secondary",
  growing: "bg-primary/20 text-primary",
}

export const experienceLabels = {
  entry: "Entry Level",
  mid: "Mid Level",
  senior: "Senior",
  lead: "Lead/Executive",
}
